## YAML Template.
---
production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: mystore_production
  pool: 5
  username: sidelineswap_dev
  password: sidelineswap_dev
  socket: /var/run/mysqld/mysqld.sock